version: '3.8'

services:
  redis:
    image: ttmo/redis-decimal:0.0.2
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./src/main/resources/lua:/lua

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
