version: '3.8'

services:
  redis:
    image: ttmo/redis-decimal:interim-0.0.2
    container_name: redis
    ports:
      - 6379:6379
    entrypoint: /usr/local/bin/redis-server --loadmodule /usr/lib/redis/modules/libdecimal.so

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
