version: '3.9'

services:
  logstash:
    image: logstash:7.10.1
    command: --config.reload.automatic
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "6044:5044"
      - "6000:5000/tcp"
      - "6000:5000/udp"
      - "10600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - docker-elk_elk

networks:
  docker-elk_elk:
    external: true
