spring:
  application:
    name: sometry
  redis:
    host: localhost
    port: 6379
  coordinate:
    zookeeper:
      zkServers: localhost:2181
lock4j:
  acquire-timeout: 3
  primary-executor: com.baomidou.lock.executor.ZookeeperLockExecutor
